version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:management
#    environment:
#      - RABBITMQ_DEFAULT_USER=user
#      - RABBITMQ_DEFAULT_PASS=secret
    ports:
      - 5672:5672
      - 15672:15672

  mongodb:
    image: mongo
#    environment:
#      - MONGO_INITDB_DATABASE=wab_4_11h
#      - MONGO_INITDB_ROOT_USERNAME=admin
#      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
#      - ME_CONFIG_BASICAUTH_USERNAME=admin
#      - ME_CONFIG_BASICAUTH_PASSWORD=pass   
    ports:
      - 8081:8081

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_MULTIPLE_DATABASES=review,coffee_shop
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d:ro
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
